import Head from "next/head";

import { FinancialProfile } from "./components";

import { useFormik } from "formik";

export default function RegisterClient() {
  const formik = useFormik({
    initialValues: {},

    onSubmit: (values) => {
      console.log(values);
    },
  });

  return (
    <>
      <Head>
        <title>Smart Evolution - Perfil Financiero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <FinancialProfile formik={formik} />
    </>
  );
}
