import Head from "next/head";

import { FinancialProfile } from "./components";

import { useFormik } from "formik";

export default function FinancialProfile() {
  const formik = useFormik({
    initialValues: {
      first_period: {},
      second_period: {},
      third_period: {},
    },

    onSubmit: (values) => {
      console.log(values);
    },
  });

  return (
    <>
      <Head>
        <title>Smart Evolution - Perfil Financiero</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FinancialProfile formik={formik} />
    </>
  );
}
