import Head from "next/head";

import { useFetch } from "@hooks/useFetch";

import { BrokerListComponent } from "./components";
import { GetBrokerList } from "./queries";

export default function BrokerList() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: GetBrokerList, init: true });

  return (
    <>
      <Head>
        <title>Consulta de corredores</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BrokerListComponent />
    </>
  );
}
