import FinancialProfile from "./components";
import Head from "next/head";

export default function RegisterClient() {
  return (
    <>
      <Head>
        <title>Smart Evolution - Perfil Financiero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <FinancialProfile />
    </>
  );
}
