import Head from "next/head";

export default function Dashboard() {
  return (
    <div>
      <Head>
        <title>Smart Evolution - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>

      {/*  <Header />
      <Navbar /> */}
    </div>
  );
}
