import Head from "next/head";

import { useFetch } from "@hooks/useFetch";

import { BrochureListComponent } from "./components";
import { GetBrochureList } from "./queries";

export default function BrochureList() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: GetBrochureList, init: true });

  return (
    <>
      <Head>
        <title>Consulta de Prospectos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BrochureListComponent />
    </>
  );
}
