import Head from "next/head";
import * as React from "react";
import { useFormik } from "formik";
import * as yup from "yup";
import { Deposit } from "./components";
import { useFetch } from "../../../shared/hooks/useFetch";
import {
  RegisterDepositQuery,
  ModifyDepositQuery,
  GetDepositByID,
} from "./queries";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export default function RegisterDeposit() {
  const [option, setOption] = useState("");
  const router = useRouter();

  useEffect(() => {
    if (router && router.query) {
      setOption(Object.values(router.query)[0]);
    }
  }, [router.query]);

  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: RegisterDepositQuery, init: false });

  const {
    fetch: fetch2,
    loading: loading2,
    error: error2,
    data: data2,
  } = useFetch({ service: GetDepositByID, init: false });

  const {
    fetch: fetch3,
    loading: loading3,
    error: error3,
    data: data3,
  } = useFetch({ service: ModifyDepositQuery, init: false });

  useEffect(() => {
    if (option !== "register" && option !== "" && option !== undefined) {
    }
  }, [option]);

  const validationSchema = yup.object({
    client: yup
      .string("Selecciona el corredor")
      .nullable(true)
      .required("El corredor es requerido"),
    
    account: yup
      .string("Selecciona la cuenta")
      .nullable(true)
      .required("La cuenta es requerida"),


    date: yup
      .string("Ingresa la fecha de giro")
      .required("La fecha es requerida"),

    amount: yup
      .string("Ingresa el monto de operación")
      .required("El monto es requerido"),

    observations: yup
      .string("Ingresa una observación")
      .nullable(true)
  });

  const initialValues = {
    client: null,
    account: null,
    amount: "",
    date: null,
    observations : "",
  };

  const formik = useFormik({
    initialValues: initialValues,
    validationSchema: validationSchema,
    onSubmit: (values) => {
      if (option === "register") {
        console.log("Registrado el giro-inversionista");
        alert(JSON.stringify(values, null, 2));
        fetch(values);
      } else {
        console.log("Actualizado el giro-inversionista");
        alert(JSON.stringify(values, null, 2));
        fetch3(values);
      }
    },
  });

  return (
    <>
      <Head>
        <title>
          {option === "register" ? "Registrar corredor" : "Modificar corredor"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <Deposit formik={formik} option={option} />
    </>
  );
}
