const sections = {
  1: "INFORMACIÓN BÁSICA DE EMPRESA",
  2: "INFORMACIÓN TRIBUTARIA",
  3: "ACTIVIDAD EN OPERACIONES INTERNACIONALES",
  4: "PARTICIPACIÓN POLÍTICA",
  5: "INFORMACIÓN DE CONTACTO",
};

export default sections;
