import { OperationsComponents } from "./components";
import Head from "next/head";

export default function Operations() {
  return (
    <>
      <Head>
        <title>Consulta de operaciones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <OperationsComponents />
    </>
  );
}
