import Head from "next/head";

import { OperationsComponents } from "./components";

export default function Operations() {
  return (
    <>
      <Head>
        <title>Consulta de operaciones</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <OperationsComponents />
    </>
  );
}
