import Head from "next/head";
import Image from "next/image";
import * as React from "react";
import { useFormik } from "formik";
import * as yup from "yup";
import { SignUpClient } from "./components";
import { useFetch } from "../../shared/hooks/useFetch";
import { RegisterClientQuery } from "./queries";

export default function RegisterClient() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: RegisterClientQuery, init: false });

  const validationSchema = yup.object({
    type_identity: yup
      .string("Ingresa el tipo de identificación del corredor")
      .nullable(true)
      .required("El tipo de identificación es requerido"),

    document_number: yup
      .string("Ingresa un número de documento")
      .matches(/^[0-9]+$/, "Ingresa un número de documento válido")
      .required("El número de documento es requerido"),

    first_name: yup
      .string("Ingresa un nombre")
      .matches(/[a-zA-Z]+/, "Ingresa un nombre válido")
      .required("El nombre es requerido"),

    last_name: yup
      .string("Ingresa un apellido")
      .matches(/^[a-zA-Z]+$/, "Ingresa un apellido válido")
      .required("El apellido es requerido"),

    email: yup
      .string("Ingresa un email")
      .matches(
        /^[a-zA-Z]+[a-zA-Z0-9_.]+@[a-zA-Z.]+[a-zA-Z]$/,
        "Ingresa un email válido"
      )
      .required("El email es requerido"),

    address: yup
      .string("Ingresa una dirección")
      .required("La dirección es requerida"),

    phone_number: yup
      .string("Ingresa un número de teléfono")
      .matches(/^[0-9]+$/, "Ingresa un número de teléfono válido")
      .required("El número de teléfono es requerido"),

    city: yup
      .string("Ingresa una ciudad")
      .nullable(true)
      .required("La ciudad es requerida"),
  });

  const formik = useFormik({
    initialValues: {
      type_identity: "",
      document_number: "",
      first_name: "",
      last_name: "",
      address: "",
      email: "",
      phone_number: "",
      city: "",
    },
    validationSchema: validationSchema,
    onSubmit: (values) => {
      fetch(values);
      alert(JSON.stringify(values, null, 2));
    },
  });

  return (
    <>
      <Head>
        <title>Registro de corredores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <SignUpClient formik={formik} />
    </>
  );
}
