import Head from "next/head";

import { FinancialInd } from "./components";

export default function FinancialIndicators() {
  return (
    <>
      <Head>
        <title>Indicadores financieros</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FinancialInd />
    </>
  );
}
