import Head from "next/head";

import { FinancialStat } from "./components";

import { useFormik } from "formik";

export default function FinancialStatement() {
  const formik = useFormik({
    initialValues: {
      first_period: {
        balance: "",
        stateOfCashflow: "",
        financialStatementAudit: "",
        managementReport: "",
        certificateOfStockOwnership: "",
        rentDeclaration: "",
        assets: {},
      },
      second_period: {
        balance: "",
        stateOfCashflow: "",
        financialStatementAudit: "",
        managementReport: "",
        certificateOfStockOwnership: "",
        rentDeclaration: "",
        assets: {},
      },
      third_period: {
        balance: "",
        stateOfCashflow: "",
        financialStatementAudit: "",
        managementReport: "",
        certificateOfStockOwnership: "",
        rentDeclaration: "",
        assets: {},
      },
    },

    onSubmit: (values) => {
      console.log(values);
    },
  });

  return (
    <>
      <Head>
        <title>Estado de situación financiera</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FinancialStat formik={formik} />
    </>
  );
}
