import Head from "next/head";

import { FinancialStat } from "./components";

export default function FinancialStatement() {
  return (
    <>
      <Head>
        <title>Estado de situación financiera</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FinancialStat />
    </>
  );
}
