import Head from "next/head";
import Image from "next/image";
import styles from "../styles/login.module.css";
import Inputs from "../components/inputs";
import { Grid} from "@mui/material";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Smart Evolution - Inicio de sesión</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>

      <Grid container spacing={0}>
        <Grid
          item
          xs={12}
          md={6}
          style={{ height: "100vh", background: "#ebebeb" }}
          display="flex"
          alignItems="center"
          justifyContent="center"
        >
          <div>
            <Image
              src="/assets/Icono Smart + Texto.svg"
              height={78}
              width={312}
              alt="Smart Evolution"
              className={styles.logo}
            />
            <Inputs />
          </div>
        </Grid>
        <Grid
          item
          xs={0}
          md={6}
          style={{ height: "100vh", background: "#b5d1c9", color: "black" }}
          display="flex"
          alignItems="center"
          justifyContent="center"
        >
          <div>
            <Image
              src="/assets/Ilustración - Inicio de sesión.svg"
              height={600}
              width={600}
            />
          </div>
        </Grid>
      </Grid>
    </div>
  );
}
