import Head from "next/head";
import Image from "next/image";
import styles from "../styles/login.module.css";
import Inputs from "../components/inputs";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Smart Evolution - Inicio de sesión</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <div className={styles.body}>
        <div className={styles.left}>
          <div className={styles.centered}>
            <Image
              src="/assets/Icono Smart + Texto.svg"
              height={78}
              width={312}
              alt="Smart Evolution"
              className={styles.logo}
            />
            <Inputs />
          </div>
        </div>
        <div className={styles.right}>
          <div className={styles.centered}>
            <Image
              src="/assets/Ilustración - Inicio de sesión.svg"
              height={700}
              width={700}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
