import Head from "next/head";
import Image from "next/image";
import * as React from "react";
import { useFormik } from "formik";
import * as yup from "yup";
import { ClientListComponent } from "./components";
import { useFetch } from "../../../shared/hooks/useFetch";
import { GetClientList } from "./queries";

export default function ClientList() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: GetClientList, init: true });

  return (
    <>
      <Head>
        <title>Consulta de clientes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>
      <ClientListComponent />
    </>
  );
}
