/* eslint-disable react-hooks/exhaustive-deps */
// Next imports
import Head from "next/head"
// Hooks
import { useFormik } from "formik"
import { useFetch } from "@hooks/useFetch"
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
// Component
import { RiskProfileC } from './components'
// Queries 
import { GetCustomerById } from './queries'


export const RiskProfileV = () => {
    // router
    const router = useRouter()

    // get the url params

    // Hooks
    const [customer, setCustomer] = useState(null)

    // get the customer data
    const {
        fetch: getCustomer,
        loading: loadingGetCustomer,
        error: errorGetCustomer,
        data: dataCustomer,
    } = useFetch({ service: GetCustomerById, init: false })

    // start the fetch
    useEffect(() => {
    if (router.query.id != undefined) getCustomer(router.query.id)
    },[router.query.id])

    // set the customer data
    useEffect(() => {
        if (dataCustomer) {
            setCustomer(dataCustomer)
        }
    }, [dataCustomer])
return (
<>
    <Head>
    <title>Perfil de riesgo</title>
    <meta name="description" content="Generated by create next app" />
    </Head>
    <RiskProfileC data={dataCustomer}/>
</>)
}