import Head from "next/head";
import Navbar from "../../components/navbar";
import Header from "../../components/header";
export default function index() {
  return (
    <div>
      <Head>
        <title>Smart Evolution - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Icono Smart.svg" />
      </Head>

      <h1>Hola mundo</h1>
    </div>
  );
}
