import Head from "next/head";

import { useFetch } from "@hooks/useFetch";

import { DepositListComponent } from "./components";
import { GetBrokerList } from "./queries";

export default function DepositList() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: GetBrokerList, init: true });

  return (
    <>
      <Head>
        <title>Consulta de giro-emisores</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DepositListComponent />
    </>
  );
}
